### ISSUE TITLE
Vulnerabilities

### ISSUE THREAD

**Issue by rsmsha** [billsonnn/habboapi#8]
When executing npm install, a few vulnerabilities are found, Is there any way to fix this?
NPM: found 6 vulnerabilities (2 low, 4 high)
This is the result of npm audit:
https://gist.github.com/rsmsha/9033321aa38517deeec00602f823d0ae

**Comment by billsonnn** [comment]
This project is old and no longer maintained. The vulnerabilities are from dependencies of some packages that HabboAPI uses. Currently I have no plans to update this release, I am working on other projects. Lookout on RZ for future developments or check my GitHub every now and then!

**Comment by rsmsha** [comment]
That's sad to hear, thanks for the great release and for the quick reply. Im looking forward to your next projects!
